### ISSUE TITLE
From and From field?

### ISSUE THREAD

**Issue by Zehra** [corenting/InflationCalculator#119]
Is this intended? Since it seems a bit confusing with both fields being listed as "From (year)".

**Comment by corenting** [comment]
Hello, thank you for reporting the issue !
It's a bug that I introduced when tweaking the input fields, I will fix it :)

**Comment by corenting** [comment]
The bug has been fixed in version 2.11 available here: https://github.com/corenting/InflationCalculator/releases/tag/v2.11.
It should be available in F-Droid and Google Play Store soon.
