### ISSUE TITLE
Data loss while using the app (the fragment disappears after double screen rotation)

### ISSUE THREAD

**Issue by davirec** [corenting/InflationCalculator#120]
When I perform these sequences of events, the fragment disappears after double screen rotation:

1. Open the app
2. Tap in About
3. A screen similar to this will appear:

Before rotation:

<img src="https://user-images.githubusercontent.com/3637419/158074175-3cbe8079-ffa5-4fd2-97ef-1741dd7378cc.png" width=30% height=30%>

4. Force the pause from the activity and then return to the activity (double screen rotation). Note that the About fragment disappears. 

The expected behavior is the return to the state of the previous image.

However, the About fragment disappears.

After rotation:

<img src="https://user-images.githubusercontent.com/3637419/158074180-c824b2d4-6e8b-4d4b-ab84-7a418f665173.png" width=30% height=30%>

Note: 
- The pause from activity(1) can be performed in several ways. We suggest using a double screen rotation (starts in portrait, goes to landscape, and back to portrait) with this function previously enabled in the smartphone.
- Double screen rotation: It is executed twice to reach a state that should be exactly the same as the screen before if no data loss occurred.
- A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values.

Device:
- Device: Moto G30 with OS: Android 11
- Version: 2.10
- Device language: English

1. https://developer.android.com/guide/components/activities/activity-lifecycle

**Comment by corenting** [comment]
Thanks for the report of this issue! I will fix it in next version :)

**Comment by davirec** [comment]
Thanks

**Comment by corenting** [comment]
The issue was fixed in [234dd27](https://github.com/corenting/InflationCalculator/commit/234dd27533274aadc05473e1fd355e91b111fd22), will be included in the next release.
