### ISSUE TITLE
Menu is light on the dark mode

### ISSUE THREAD

**Issue by xmha97** [corenting/InflationCalculator#154]
Hi,
Menu is light on the dark mode.
![Screenshot_2022-12-08-04-41-53-149_fr corenting convertisseureurofranc](https://user-images.githubusercontent.com/23485114/206331877-34a0bdff-d0c4-4b29-b18f-14a28eea41f1.jpg)

**Comment by corenting** [comment]
Thanks for reporting the issue! this is caused by the theme changes in the last update, I will work on fixing it .

**Comment by corenting** [comment]
The issue has been fixed in version 2.13, available now on Github releases and soon on Google Play and F-Droid.
