### ISSUE TITLE
Coefficient INSEE 2022

### ISSUE THREAD

**Issue by guy-teube** [corenting/InflationCalculator#169]
Bonjour,
L'INSEE a publié le [coefficient pour 2022](https://www.insee.fr/fr/statistiques/serie/010605954).
Serait-il possible de l'ajouter à l'application ?
Je voudrais faire une PR mais je sais connais pas le code de l'appli. Avec un petit conseil pour débuter, je pourrais proposer la PR :)
Merci d'avance.

**Comment by corenting** [comment]
Bonjour! Merci pour la proposition de PR, mais je viens d'ajouter les coefficients 2022 dans la version 2.14 publiée dimanche, elle devrait arriver progressivement sur le Play Store et F-Droid.

Pour information je stocke les coefficients dans le dossier 'raw' des ressources : https://github.com/corenting/InflationCalculator/tree/master/app/src/main/res/raw et ils sont ensuite chargés au démarrage de l'app.
