### ISSUE TITLE
permission_ add buymeacoffee or kofi as donate link on fdroid

### ISSUE THREAD

**Issue by ghost** [corenting/InflationCalculator#189]
@corenting 
* is it **ok to add** buymeacoffee or kofi link given in repo? please specify your choice :)
* buymeacoffee or kofi link in [app fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/fr.corenting.convertisseureurofranc.yml) will create a link on fdroid client

**Comment by corenting** [comment]
Hello! [A MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13709) has been submitted to add the new donation link in the fdroid metadata file.

**Comment by corenting** [comment]
The link has been added to fdroid, closing the issue
