### ISSUE TITLE
Request for the Addition of a Korean Inflation Calculator

### ISSUE THREAD

**Issue by ilotoki0804** [corenting/InflationCalculator#195]
I'm grateful for your app's feature that allows estimation of historical monetary values. If possible, could you add a feature to support KRW? You might find [this file](https://github.com/corenting/InflationCalculator/files/12549301/kr_values.csv) ([source](https://www.index.go.kr/unity/potal/indicator/PotalIdxSearch.do?idxCd=4226&sttsCd=422601&clas_div=&idx_sys_cd=)) useful for the implementation. Thank you for considering this suggestion.

**Comment by corenting** [comment]
Hello! Thanks for your message.

I started working on adding South Korea: #197

**Comment by ilotoki0804** [comment]
Thank you for taking the time to implement these changes! Your efforts are greatly appreciated. Have a nice day :)

**Comment by corenting** [comment]
It has been added in version 2.15 which should appear soon on the Play-Store or F-Droid. You can also download the apk directly [here](https://github.com/corenting/InflationCalculator/releases/download/v2.15/app-release.apk)

**Comment by ilotoki0804** [comment]
It appears to malfunction upon selecting 'Wons' for currency. Could you please check this issue?

**Comment by corenting** [comment]
Thanks for the report ! I removed the download from GitHub and will reupload a fixed version shortly
