### ISSUE TITLE
Add more currencies

### ISSUE THREAD

**Issue by inson1** [corenting/InflationCalculator#204]
For example CZK, Polish Zloty and EUR (whole eurozone) would be great

**Comment by corenting** [comment]
Sorry for the delay in answering, thanks for the suggestion! 
I will try to add more currencies in the next release as I need to push an update soon anyway for the new 2023 values .

**Comment by inson1** [comment]
@corenting btw with that you could unite fastline desctription with Readme, I mean the text

**Comment by corenting** [comment]
I created a new issue #228 to regroup all currencies suggestion, closing this issue in favor of the other one.

**Comment by inson1** [comment]
@corenting done, pr created, just need translating
